name: 'Arduino CLI Setup'
description: 'Download and setup Arduino CLI'

runs:
  using: "composite"
  steps:
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install core
      shell: bash
      run: |
        arduino-cli core update-index
        arduino-cli core install arduino:avr

    - name: Install libraries
      shell: bash
      run: |
        if [ -f src/libraries-list.txt ]; then
          while IFS= read -r library; do
            if [ -n "$library" ]; then
              arduino-cli lib install "$library"
            fi
          done < src/libraries-list.txt
        fi
